Repository aicers/giganto, pull requests merged in 2022-09, with the labels that each got.

#41 Remove redundant `Arc`
  src/ingestion.rs
Labels: refactor

#43 Make `storage::retention_periodically` format-independent
  src/main.rs
  src/storage.rs
Labels: refactor

#53 Use num-enum to derive `TryFrom<u32>` for `RecordType`
  Cargo.lock
  Cargo.toml
  src/ingestion.rs
Labels: refactor

#69 Modify retain logic
  src/storage.rs
Labels: performance

#71 Modify key value struct
  src/graphql.rs
  src/ingestion.rs
  src/storage.rs
Labels: bug, refactor

#74 Remove unnecessary `pub`
  src/graphql.rs
Labels: refactor

#68 Decouple web module from graphql
  src/graphql.rs
  src/web.rs
Labels: refactor

#88 Parse addresses during config parsing
  src/ingestion.rs
  src/main.rs
  src/publish.rs
  src/settings.rs
Labels: refactor

#94 Correct the time unit of DNS search query
  src/storage.rs
Labels: bug

#95 Remove unnecessary memory allocation
  src/graphql/log.rs
  src/graphql/network.rs
  src/storage.rs
Labels: performance

#98 Parse config variables at read
  Cargo.lock
  Cargo.toml
  src/ingestion.rs
  src/main.rs
  src/publish.rs
  src/settings.rs
Labels: refactor

#100 Remove redundant arguments
  src/ingestion.rs
  src/main.rs
  src/publish.rs
  src/web.rs
Labels: refactor

#106 Document key incompatibility in `web::serve`
  clippy.toml
  src/main.rs
  src/web.rs
Labels: documentation

#110 Move pagination logic from storage to graphql
  src/graphql.rs
  src/graphql/log.rs
  src/graphql/network.rs
  src/publish.rs
  src/storage.rs
Labels: bug, refactor
