Repository aicers/giganto, pull requests merged in 2022-12, with the labels that each got.

#192 Fix timeseries publish logic
  src/ingestion.rs
  src/publish.rs
  src/publish/tests.rs
Labels: bug

#194 Make network event names conform to Zeek's naming
  src/graphql/network.rs
  src/ingestion.rs
  src/ingestion/tests.rs
  src/publish/tests.rs
  src/storage.rs
Labels: refactor

#205 타입 이름 수정
  src/ingestion.rs
Labels: refactor

#209 Implement the display trait on raw data structs
  src/ingestion.rs
  src/ingestion/network.rs
Labels: refactor

#217 Simplify iterator usage with `Iterator::take`
  src/publish.rs
Labels: refactor

#221 Replace `loop`-`if`-`let` with `while`-`let`
  src/storage.rs
Labels: refactor

#225 Remove unnecessary memory allocation
  src/storage.rs
Labels: performance

#227 Replace `for` with an iterator to simplify code
  src/storage.rs
Labels: refactor
